"""
Athena Studio V1 - Production Exercise Library
Complete catalog of evidence-informed, calm guided exercises.
Includes natural pauses (pause_after_seconds) and exact text-voice alignment.
Zero medical claims, zero fake statistics.
"""

from typing import List, Dict, Any, Optional

STUDIO_EXERCISES: List[Dict[str, Any]] = [
    {
        "id": "two_minute_reset",
        "slug": "two-minute-reset",
        "title": "2-Minute Reset",
        "category": "RESET",
        "duration_seconds": 120,
        "duration_minutes": 2,
        "duration_label": "2 min",
        "purpose": "A short guided pause when your mind feels busy.",
        "description": "A short guided pause when your mind feels busy.",
        "difficulty": "Gentle",
        "active": True,
        "caution": None,
        "steps": [
            {
                "id": "two_min_1",
                "exercise_id": "two_minute_reset",
                "step_order": 1,
                "instruction_text": "Pause where you are.",
                "voice_text": "Let's begin by taking a quiet pause right where you are.",
                "duration_seconds": 12,
                "pause_after_seconds": 4,
                "instruction_type": "pause",
            },
            {
                "id": "two_min_2",
                "exercise_id": "two_minute_reset",
                "step_order": 2,
                "instruction_text": "Let your shoulders soften, if that feels comfortable.",
                "voice_text": "Let your shoulders soften. Release any tension in your jaw.",
                "duration_seconds": 18,
                "pause_after_seconds": 5,
                "instruction_type": "somatic",
            },
            {
                "id": "two_min_3",
                "exercise_id": "two_minute_reset",
                "step_order": 3,
                "instruction_text": "Take a slow, comfortable breath.",
                "voice_text": "Take a slow, comfortable breath. Inhale gently... and let it leave slowly.",
                "duration_seconds": 22,
                "pause_after_seconds": 6,
                "instruction_type": "breathe",
            },
            {
                "id": "two_min_4",
                "exercise_id": "two_minute_reset",
                "step_order": 4,
                "instruction_text": "Notice what feels most present right now.",
                "voice_text": "Notice what feels most present right now, without needing to change anything.",
                "duration_seconds": 24,
                "pause_after_seconds": 6,
                "instruction_type": "notice",
            },
            {
                "id": "two_min_5",
                "exercise_id": "two_minute_reset",
                "step_order": 5,
                "instruction_text": "You don't need to solve anything during this pause.",
                "voice_text": "You don't need to solve anything during this pause. Just be here.",
                "duration_seconds": 24,
                "pause_after_seconds": 5,
                "instruction_type": "permission",
            },
            {
                "id": "two_min_6",
                "exercise_id": "two_minute_reset",
                "step_order": 6,
                "instruction_text": "Take one final comfortable breath, and return when you're ready.",
                "voice_text": "Take one final comfortable breath. When you are ready, gently return.",
                "duration_seconds": 20,
                "pause_after_seconds": 4,
                "instruction_type": "closing",
            },
        ],
    },
    {
        "id": "box_breathing",
        "slug": "box-breathing",
        "title": "Box Breathing",
        "category": "BREATHE",
        "duration_seconds": 240,
        "duration_minutes": 4,
        "duration_label": "4 min",
        "purpose": "A structured breathing practice for settling the body.",
        "description": "A structured breathing practice for settling the body.",
        "difficulty": "Gentle",
        "active": True,
        "caution": "If holding your breath feels uncomfortable, skip the holds and breathe naturally.",
        "default_pacing": {"inhale": 4, "hold1": 4, "exhale": 4, "hold2": 4},
        "steps": [
            {
                "id": "box_1",
                "exercise_id": "box_breathing",
                "step_order": 1,
                "instruction_text": "Settle into a comfortable posture with your feet supported.",
                "voice_text": "Let's begin by settling into a comfortable position.",
                "duration_seconds": 12,
                "pause_after_seconds": 3,
                "instruction_type": "prepare",
            },
            {
                "id": "box_2",
                "exercise_id": "box_breathing",
                "step_order": 2,
                "instruction_text": "Take a slow breath in through your nose.",
                "voice_text": "Slowly breathe in through your nose.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "inhale",
            },
            {
                "id": "box_3",
                "exercise_id": "box_breathing",
                "step_order": 3,
                "instruction_text": "Gently hold.",
                "voice_text": "Gently hold for four seconds.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "hold",
            },
            {
                "id": "box_4",
                "exercise_id": "box_breathing",
                "step_order": 4,
                "instruction_text": "Slowly breathe out.",
                "voice_text": "Slowly breathe out.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "exhale",
            },
            {
                "id": "box_5",
                "exercise_id": "box_breathing",
                "step_order": 5,
                "instruction_text": "Pause and hold empty.",
                "voice_text": "Pause and hold empty.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "hold",
            },
            {
                "id": "box_6",
                "exercise_id": "box_breathing",
                "step_order": 6,
                "instruction_text": "Take a slow breath in through your nose.",
                "voice_text": "Slowly breathe in.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "inhale",
            },
            {
                "id": "box_7",
                "exercise_id": "box_breathing",
                "step_order": 7,
                "instruction_text": "Gently hold.",
                "voice_text": "Hold gently.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "hold",
            },
            {
                "id": "box_8",
                "exercise_id": "box_breathing",
                "step_order": 8,
                "instruction_text": "Slowly breathe out.",
                "voice_text": "And now let the breath leave slowly.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "exhale",
            },
            {
                "id": "box_9",
                "exercise_id": "box_breathing",
                "step_order": 9,
                "instruction_text": "Pause and hold empty.",
                "voice_text": "Pause empty.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "hold",
            },
            {
                "id": "box_10",
                "exercise_id": "box_breathing",
                "step_order": 10,
                "instruction_text": "Take a slow breath in through your nose.",
                "voice_text": "Breathe in.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "inhale",
            },
            {
                "id": "box_11",
                "exercise_id": "box_breathing",
                "step_order": 11,
                "instruction_text": "Gently hold.",
                "voice_text": "Hold.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "hold",
            },
            {
                "id": "box_12",
                "exercise_id": "box_breathing",
                "step_order": 12,
                "instruction_text": "Slowly breathe out.",
                "voice_text": "Breathe out.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "exhale",
            },
            {
                "id": "box_13",
                "exercise_id": "box_breathing",
                "step_order": 13,
                "instruction_text": "Pause and hold empty.",
                "voice_text": "Pause empty.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "hold",
            },
            {
                "id": "box_14",
                "exercise_id": "box_breathing",
                "step_order": 14,
                "instruction_text": "Take a slow breath in through your nose.",
                "voice_text": "Slow inhale.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "inhale",
            },
            {
                "id": "box_15",
                "exercise_id": "box_breathing",
                "step_order": 15,
                "instruction_text": "Gently hold.",
                "voice_text": "Gentle hold.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "hold",
            },
            {
                "id": "box_16",
                "exercise_id": "box_breathing",
                "step_order": 16,
                "instruction_text": "Slowly breathe out.",
                "voice_text": "Smooth exhale.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "exhale",
            },
            {
                "id": "box_17",
                "exercise_id": "box_breathing",
                "step_order": 17,
                "instruction_text": "Pause and hold empty.",
                "voice_text": "Hold empty.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "hold",
            },
            {
                "id": "box_18",
                "exercise_id": "box_breathing",
                "step_order": 18,
                "instruction_text": "Allow your breathing to return to its natural rhythm.",
                "voice_text": "Allow your breathing to return to its natural rhythm. Notice how your body feels.",
                "duration_seconds": 16,
                "pause_after_seconds": 3,
                "instruction_type": "closing",
            },
        ],
    },
    {
        "id": "extended_exhale",
        "slug": "extended-exhale",
        "title": "Extended Exhale",
        "category": "BREATHE",
        "duration_seconds": 300,
        "duration_minutes": 5,
        "duration_label": "5 min",
        "purpose": "Gentle inhale followed by a longer exhale.",
        "description": "Gentle inhale followed by a longer exhale.",
        "difficulty": "Gentle",
        "active": True,
        "caution": "Breathe gently without straining your lungs.",
        "steps": [
            {
                "id": "ee_1",
                "exercise_id": "extended_exhale",
                "step_order": 1,
                "instruction_text": "Rest comfortably and allow your posture to settle.",
                "voice_text": "Let's begin by resting comfortably. Let your shoulders drop.",
                "duration_seconds": 15,
                "pause_after_seconds": 4,
                "instruction_type": "prepare",
            },
            {
                "id": "ee_2",
                "exercise_id": "extended_exhale",
                "step_order": 2,
                "instruction_text": "Inhale gently through your nose for 4 seconds.",
                "voice_text": "Inhale gently for four seconds.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "inhale",
            },
            {
                "id": "ee_3",
                "exercise_id": "extended_exhale",
                "step_order": 3,
                "instruction_text": "Exhale slowly and completely for 7 seconds.",
                "voice_text": "Now exhale slowly and completely, letting everything soften.",
                "duration_seconds": 7,
                "pause_after_seconds": 0,
                "instruction_type": "exhale",
            },
            {
                "id": "ee_4",
                "exercise_id": "extended_exhale",
                "step_order": 4,
                "instruction_text": "Inhale gently for 4 seconds.",
                "voice_text": "Inhale gently.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "inhale",
            },
            {
                "id": "ee_5",
                "exercise_id": "extended_exhale",
                "step_order": 5,
                "instruction_text": "Exhale slowly for 7 seconds.",
                "voice_text": "Long, slow exhale.",
                "duration_seconds": 7,
                "pause_after_seconds": 0,
                "instruction_type": "exhale",
            },
            {
                "id": "ee_6",
                "exercise_id": "extended_exhale",
                "step_order": 6,
                "instruction_text": "Inhale gently for 4 seconds.",
                "voice_text": "Inhale.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "inhale",
            },
            {
                "id": "ee_7",
                "exercise_id": "extended_exhale",
                "step_order": 7,
                "instruction_text": "Exhale slowly for 7 seconds.",
                "voice_text": "Slow, steady release.",
                "duration_seconds": 7,
                "pause_after_seconds": 0,
                "instruction_type": "exhale",
            },
            {
                "id": "ee_8",
                "exercise_id": "extended_exhale",
                "step_order": 8,
                "instruction_text": "Inhale gently for 4 seconds.",
                "voice_text": "Inhale.",
                "duration_seconds": 4,
                "pause_after_seconds": 0,
                "instruction_type": "inhale",
            },
            {
                "id": "ee_9",
                "exercise_id": "extended_exhale",
                "step_order": 9,
                "instruction_text": "Exhale slowly for 7 seconds.",
                "voice_text": "And exhale completely.",
                "duration_seconds": 7,
                "pause_after_seconds": 0,
                "instruction_type": "exhale",
            },
            {
                "id": "ee_10",
                "exercise_id": "extended_exhale",
                "step_order": 10,
                "instruction_text": "Rest naturally in the quiet space you created.",
                "voice_text": "Rest naturally in this quiet space. Notice the calm in your nervous system.",
                "duration_seconds": 20,
                "pause_after_seconds": 4,
                "instruction_type": "closing",
            },
        ],
    },
    {
        "id": "five_minute_grounding",
        "slug": "5-minute-grounding",
        "title": "5-Minute Grounding",
        "category": "GROUND",
        "duration_seconds": 300,
        "duration_minutes": 5,
        "duration_label": "5 min",
        "purpose": "Bring your attention back to the present moment.",
        "description": "Bring your attention back to the present moment.",
        "difficulty": "Gentle",
        "active": True,
        "caution": "Take your time with each sense. There is no rush.",
        "steps": [
            {
                "id": "gr_1",
                "exercise_id": "five_minute_grounding",
                "step_order": 1,
                "instruction_text": "Bring your attention to where you are right now. Feel your feet supported.",
                "voice_text": "Let's take a moment here. Feel your feet resting on the ground.",
                "duration_seconds": 25,
                "pause_after_seconds": 5,
                "instruction_type": "prepare",
            },
            {
                "id": "gr_2",
                "exercise_id": "five_minute_grounding",
                "step_order": 2,
                "instruction_text": "Look around you and notice 5 things you can see.",
                "voice_text": "Look around your space, and gently notice five things you can see.",
                "duration_seconds": 50,
                "pause_after_seconds": 8,
                "instruction_type": "sense_see",
            },
            {
                "id": "gr_3",
                "exercise_id": "five_minute_grounding",
                "step_order": 3,
                "instruction_text": "Notice 4 things you can physically feel.",
                "voice_text": "Now notice four things you can physically feel. The fabric of your clothes, or the air on your hands.",
                "duration_seconds": 50,
                "pause_after_seconds": 8,
                "instruction_type": "sense_touch",
            },
            {
                "id": "gr_4",
                "exercise_id": "five_minute_grounding",
                "step_order": 4,
                "instruction_text": "Listen carefully for 3 things you can hear.",
                "voice_text": "Listen gently for three sounds around you, near or far.",
                "duration_seconds": 50,
                "pause_after_seconds": 8,
                "instruction_type": "sense_hear",
            },
            {
                "id": "gr_5",
                "exercise_id": "five_minute_grounding",
                "step_order": 5,
                "instruction_text": "Notice 2 things you can smell around you.",
                "voice_text": "Notice two things you can smell in this moment.",
                "duration_seconds": 45,
                "pause_after_seconds": 6,
                "instruction_type": "sense_smell",
            },
            {
                "id": "gr_6",
                "exercise_id": "five_minute_grounding",
                "step_order": 6,
                "instruction_text": "Notice 1 thing you can appreciate right now.",
                "voice_text": "Notice one thing you can appreciate about this quiet pause.",
                "duration_seconds": 45,
                "pause_after_seconds": 6,
                "instruction_type": "sense_taste",
            },
            {
                "id": "gr_7",
                "exercise_id": "five_minute_grounding",
                "step_order": 7,
                "instruction_text": "You are right here, anchored and safe in this moment.",
                "voice_text": "You are right here, anchored and present in this moment.",
                "duration_seconds": 35,
                "pause_after_seconds": 4,
                "instruction_type": "closing",
            },
        ],
    },
    {
        "id": "evening_wind_down",
        "slug": "evening-wind-down",
        "title": "Evening Wind-Down",
        "category": "UNWIND",
        "duration_seconds": 420,
        "duration_minutes": 7,
        "duration_label": "7 min",
        "purpose": "A slower practice designed for the end of the day.",
        "description": "A slower practice designed for the end of the day.",
        "difficulty": "Gentle",
        "active": True,
        "caution": None,
        "steps": [
            {
                "id": "ew_1",
                "exercise_id": "evening_wind_down",
                "step_order": 1,
                "instruction_text": "Let go of whatever needed to be done today.",
                "voice_text": "Let's take a moment to release the day. Nothing more needs to be accomplished.",
                "duration_seconds": 55,
                "pause_after_seconds": 6,
                "instruction_type": "release",
            },
            {
                "id": "ew_2",
                "exercise_id": "evening_wind_down",
                "step_order": 2,
                "instruction_text": "Allow your jaw to unclench and your forehead to soften.",
                "voice_text": "Allow your jaw to unclench, and let the space between your eyebrows soften.",
                "duration_seconds": 65,
                "pause_after_seconds": 8,
                "instruction_type": "somatic",
            },
            {
                "id": "ew_3",
                "exercise_id": "evening_wind_down",
                "step_order": 3,
                "instruction_text": "Take a slow, unhurried breath all the way down to your belly.",
                "voice_text": "Take a slow, unhurried breath all the way down to your belly.",
                "duration_seconds": 75,
                "pause_after_seconds": 8,
                "instruction_type": "breathe",
            },
            {
                "id": "ew_4",
                "exercise_id": "evening_wind_down",
                "step_order": 4,
                "instruction_text": "Let any thoughts pass by without engaging them.",
                "voice_text": "When thoughts arise, let them drift past without needing to hold onto them.",
                "duration_seconds": 80,
                "pause_after_seconds": 8,
                "instruction_type": "mind",
            },
            {
                "id": "ew_5",
                "exercise_id": "evening_wind_down",
                "step_order": 5,
                "instruction_text": "Settle into restful stillness.",
                "voice_text": "Settle into this restful stillness. You have done enough today.",
                "duration_seconds": 85,
                "pause_after_seconds": 8,
                "instruction_type": "rest",
            },
            {
                "id": "ew_6",
                "exercise_id": "evening_wind_down",
                "step_order": 6,
                "instruction_text": "Rest well.",
                "voice_text": "Rest well. Carry this calm into your evening.",
                "duration_seconds": 60,
                "pause_after_seconds": 5,
                "instruction_type": "closing",
            },
        ],
    },
    {
        "id": "mindful_focus_reset",
        "slug": "mindful-focus-reset",
        "title": "Mindful Focus Reset",
        "category": "FOCUS",
        "duration_seconds": 300,
        "duration_minutes": 5,
        "duration_label": "5 min",
        "purpose": "A short practice before returning to work.",
        "description": "A short practice before returning to work.",
        "difficulty": "Gentle",
        "active": True,
        "caution": None,
        "steps": [
            {
                "id": "mf_1",
                "exercise_id": "mindful_focus_reset",
                "step_order": 1,
                "instruction_text": "Close open mental tabs. Pause where you are.",
                "voice_text": "Before you return to work, let's close the open mental tabs and pause.",
                "duration_seconds": 45,
                "pause_after_seconds": 6,
                "instruction_type": "prepare",
            },
            {
                "id": "mf_2",
                "exercise_id": "mindful_focus_reset",
                "step_order": 2,
                "instruction_text": "Rest your attention on the steady sensation of breathing.",
                "voice_text": "Rest your attention on the steady sensation of each breath.",
                "duration_seconds": 65,
                "pause_after_seconds": 8,
                "instruction_type": "anchor",
            },
            {
                "id": "mf_3",
                "exercise_id": "mindful_focus_reset",
                "step_order": 3,
                "instruction_text": "Identify the single next task you intend to do.",
                "voice_text": "Quietly identify the single next task you intend to do. Just one thing.",
                "duration_seconds": 65,
                "pause_after_seconds": 8,
                "instruction_type": "clarity",
            },
            {
                "id": "mf_4",
                "exercise_id": "mindful_focus_reset",
                "step_order": 4,
                "instruction_text": "Commit to working on only this task with calm presence.",
                "voice_text": "Give yourself permission to work on only this task, with calm presence.",
                "duration_seconds": 65,
                "pause_after_seconds": 8,
                "instruction_type": "intent",
            },
            {
                "id": "mf_5",
                "exercise_id": "mindful_focus_reset",
                "step_order": 5,
                "instruction_text": "Take a steady breath, and begin when you're ready.",
                "voice_text": "Take one steady breath, and begin when you are ready.",
                "duration_seconds": 60,
                "pause_after_seconds": 5,
                "instruction_type": "closing",
            },
        ],
    },
    {
        "id": "body_scan",
        "slug": "body-scan",
        "title": "Body Scan",
        "category": "RELAXATION",
        "duration_seconds": 420,
        "duration_minutes": 7,
        "duration_label": "7 min",
        "purpose": "Slow attention through different body areas.",
        "description": "Slow attention through different body areas.",
        "difficulty": "Gentle",
        "active": True,
        "caution": None,
        "steps": [
            {
                "id": "bs_1",
                "exercise_id": "body_scan",
                "step_order": 1,
                "instruction_text": "Find a supported posture and allow your eyes to gently close or soften.",
                "voice_text": "Let's settle into the body. Find a comfortable, supported posture.",
                "duration_seconds": 40,
                "pause_after_seconds": 6,
                "instruction_type": "prepare",
            },
            {
                "id": "bs_2",
                "exercise_id": "body_scan",
                "step_order": 2,
                "instruction_text": "Bring awareness down to your feet, toes, and ankles.",
                "voice_text": "Bring your awareness down to your feet, your toes, and your ankles. Notice any warmth or contact.",
                "duration_seconds": 60,
                "pause_after_seconds": 8,
                "instruction_type": "scan_feet",
            },
            {
                "id": "bs_3",
                "exercise_id": "body_scan",
                "step_order": 3,
                "instruction_text": "Move your attention upward to your legs, knees, and hips.",
                "voice_text": "Move your attention upward through your calves, your knees, and your hips.",
                "duration_seconds": 60,
                "pause_after_seconds": 8,
                "instruction_type": "scan_legs",
            },
            {
                "id": "bs_4",
                "exercise_id": "body_scan",
                "step_order": 4,
                "instruction_text": "Notice your abdomen, lower back, and chest rising with each breath.",
                "voice_text": "Notice your abdomen and chest rising and falling naturally.",
                "duration_seconds": 65,
                "pause_after_seconds": 8,
                "instruction_type": "scan_torso",
            },
            {
                "id": "bs_5",
                "exercise_id": "body_scan",
                "step_order": 5,
                "instruction_text": "Release your shoulders, letting arms and hands rest heavy.",
                "voice_text": "Let your shoulders soften and drop. Let your arms and hands rest heavy.",
                "duration_seconds": 65,
                "pause_after_seconds": 8,
                "instruction_type": "scan_shoulders",
            },
            {
                "id": "bs_6",
                "exercise_id": "body_scan",
                "step_order": 6,
                "instruction_text": "Soften your neck, jaw, cheeks, and forehead.",
                "voice_text": "Notice your neck, your jaw, and the delicate muscles around your eyes. Let them release.",
                "duration_seconds": 65,
                "pause_after_seconds": 8,
                "instruction_type": "scan_head",
            },
            {
                "id": "bs_7",
                "exercise_id": "body_scan",
                "step_order": 7,
                "instruction_text": "Feel your whole body resting as one peaceful presence.",
                "voice_text": "Feel your entire body resting as one calm, integrated presence. When you're ready, return gently.",
                "duration_seconds": 65,
                "pause_after_seconds": 6,
                "instruction_type": "closing",
            },
        ],
    },
    {
        "id": "three_minute_pause",
        "slug": "three-minute-pause",
        "title": "3-Minute Mental Pause",
        "category": "RESET",
        "duration_seconds": 180,
        "duration_minutes": 3,
        "duration_label": "3 min",
        "purpose": "A gentle pause when your mind feels full or hurried.",
        "description": "A gentle pause when your mind feels full or hurried.",
        "difficulty": "Gentle",
        "active": True,
        "caution": None,
        "steps": [
            {
                "id": "tmp_1",
                "exercise_id": "three_minute_pause",
                "step_order": 1,
                "instruction_text": "Step out of whatever you were thinking about.",
                "voice_text": "Step back from whatever was occupying your mind. Give yourself permission to pause.",
                "duration_seconds": 25,
                "pause_after_seconds": 4,
                "instruction_type": "prepare",
            },
            {
                "id": "tmp_2",
                "exercise_id": "three_minute_pause",
                "step_order": 2,
                "instruction_text": "Feel the support beneath you.",
                "voice_text": "Feel the chair or ground beneath you. Let your weight settle completely.",
                "duration_seconds": 35,
                "pause_after_seconds": 5,
                "instruction_type": "somatic",
            },
            {
                "id": "tmp_3",
                "exercise_id": "three_minute_pause",
                "step_order": 3,
                "instruction_text": "Notice three natural breaths without changing them.",
                "voice_text": "Follow three breaths as they arrive and leave. Don't try to change them.",
                "duration_seconds": 45,
                "pause_after_seconds": 6,
                "instruction_type": "breathe",
            },
            {
                "id": "tmp_4",
                "exercise_id": "three_minute_pause",
                "step_order": 4,
                "instruction_text": "Let your thoughts pass like clouds across the sky.",
                "voice_text": "If thoughts arise, let them float past like clouds. You don't have to follow them.",
                "duration_seconds": 45,
                "pause_after_seconds": 5,
                "instruction_type": "mind",
            },
            {
                "id": "tmp_5",
                "exercise_id": "three_minute_pause",
                "step_order": 5,
                "instruction_text": "Return with clarity and ease.",
                "voice_text": "Take a deep, nourishing breath. And when you feel ready, bring your eyes back open.",
                "duration_seconds": 30,
                "pause_after_seconds": 4,
                "instruction_type": "closing",
            },
        ],
    },
]

STUDIO_CATEGORIES = ["ALL", "RESET", "BREATHE", "GROUND", "UNWIND", "WIND DOWN", "FOCUS", "RELAXATION", "REFLECT"]

# Aliases for backwards compatibility with previous IDs
EXERCISE_ALIASES = {
    "grounding_reset": "five_minute_grounding",
    "pre_sleep_wind_down": "evening_wind_down",
    "focus_reset": "mindful_focus_reset",
    "morning_centering": "mindful_focus_reset",
    "stress_release": "two_minute_reset",
    "mindful_pause": "two_minute_reset",
}


def get_all_exercises() -> List[Dict[str, Any]]:
    """Returns the full list of evidence-informed studio exercises."""
    return STUDIO_EXERCISES


def get_exercise_by_id(exercise_id: str) -> Optional[Dict[str, Any]]:
    """Returns a single exercise definition by ID or slug with alias resolution."""
    target_id = EXERCISE_ALIASES.get(exercise_id, exercise_id)
    for ex in STUDIO_EXERCISES:
        if ex["id"] == target_id or ex.get("slug") == target_id or ex["id"] == exercise_id or ex.get("slug") == exercise_id:
            return ex
    return None
